// Generated by gencpp from file sensor_interface/Pressure.msg
// DO NOT EDIT!


#ifndef SENSOR_INTERFACE_MESSAGE_PRESSURE_H
#define SENSOR_INTERFACE_MESSAGE_PRESSURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_interface
{
template <class ContainerAllocator>
struct Pressure_
{
  typedef Pressure_<ContainerAllocator> Type;

  Pressure_()
    : pressure(0.0)  {
    }
  Pressure_(const ContainerAllocator& _alloc)
    : pressure(0.0)  {
  (void)_alloc;
    }



   typedef float _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::sensor_interface::Pressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_interface::Pressure_<ContainerAllocator> const> ConstPtr;

}; // struct Pressure_

typedef ::sensor_interface::Pressure_<std::allocator<void> > Pressure;

typedef boost::shared_ptr< ::sensor_interface::Pressure > PressurePtr;
typedef boost::shared_ptr< ::sensor_interface::Pressure const> PressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_interface::Pressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_interface::Pressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_interface::Pressure_<ContainerAllocator1> & lhs, const ::sensor_interface::Pressure_<ContainerAllocator2> & rhs)
{
  return lhs.pressure == rhs.pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_interface::Pressure_<ContainerAllocator1> & lhs, const ::sensor_interface::Pressure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_interface::Pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_interface::Pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_interface::Pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_interface::Pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_interface::Pressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_interface::Pressure_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_interface::Pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d08eeab8c09d2ba14f8144e3bbf40d21";
  }

  static const char* value(const ::sensor_interface::Pressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd08eeab8c09d2ba1ULL;
  static const uint64_t static_value2 = 0x4f8144e3bbf40d21ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_interface::Pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_interface/Pressure";
  }

  static const char* value(const ::sensor_interface::Pressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_interface::Pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pressure\n"
"\n"
;
  }

  static const char* value(const ::sensor_interface::Pressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_interface::Pressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_interface::Pressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_interface::Pressure_<ContainerAllocator>& v)
  {
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_INTERFACE_MESSAGE_PRESSURE_H
