// Generated by gencpp from file sensor_interface/Temperature.msg
// DO NOT EDIT!


#ifndef SENSOR_INTERFACE_MESSAGE_TEMPERATURE_H
#define SENSOR_INTERFACE_MESSAGE_TEMPERATURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_interface
{
template <class ContainerAllocator>
struct Temperature_
{
  typedef Temperature_<ContainerAllocator> Type;

  Temperature_()
    : temperature(0.0)  {
    }
  Temperature_(const ContainerAllocator& _alloc)
    : temperature(0.0)  {
  (void)_alloc;
    }



   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::sensor_interface::Temperature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_interface::Temperature_<ContainerAllocator> const> ConstPtr;

}; // struct Temperature_

typedef ::sensor_interface::Temperature_<std::allocator<void> > Temperature;

typedef boost::shared_ptr< ::sensor_interface::Temperature > TemperaturePtr;
typedef boost::shared_ptr< ::sensor_interface::Temperature const> TemperatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_interface::Temperature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_interface::Temperature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_interface::Temperature_<ContainerAllocator1> & lhs, const ::sensor_interface::Temperature_<ContainerAllocator2> & rhs)
{
  return lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_interface::Temperature_<ContainerAllocator1> & lhs, const ::sensor_interface::Temperature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_interface::Temperature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_interface::Temperature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_interface::Temperature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_interface::Temperature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_interface::Temperature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_interface::Temperature_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_interface::Temperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "694ab1a51fd38693b5cadd94c1ae252d";
  }

  static const char* value(const ::sensor_interface::Temperature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x694ab1a51fd38693ULL;
  static const uint64_t static_value2 = 0xb5cadd94c1ae252dULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_interface::Temperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_interface/Temperature";
  }

  static const char* value(const ::sensor_interface::Temperature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_interface::Temperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 temperature\n"
"\n"
;
  }

  static const char* value(const ::sensor_interface::Temperature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_interface::Temperature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Temperature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_interface::Temperature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_interface::Temperature_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_INTERFACE_MESSAGE_TEMPERATURE_H
